Sila-Money/sila-sdk-demo

src/components/common/SettingsModal.js
Issue resolved, incorrect warning message display on App Setting screen.
=> SILA-2236: Issue resolved, incorrect warning message display on App Setting screen.

src/components/register/RegisterUserForm.js, src/views/kyb/RegisterBusiness.js
- For better user experience, now added `SSN` and `EIN` format on the register page in the `KYC` and `KYB` flow.
=> SILA-2245: For better user experience, now added SSN and EIN format on the register page in the KYC and KYB flow.

src/assets/styles/_dropdown.scss
Now, added a vertical scroll bar for `select dropdown` through the demo app.
=> SILA-2246 - Added vertical scroll bar for select dropdown.

src/components/register/RegisterUserForm.js, src/views/kyb/RegisterBusiness.js
Ticket request changes have been done.
=> SILA-2245: Ticket request changes have been done.

src/views/kyb/RegisterBusiness.js
Added absolute URL in the `Business Website` input as a placeholder.
=> SILA-2340: Added absolute URL in the Business Website input as a placeholder.

src/views/kyb/RegisterBusiness.js
`EIN` validation message has been updated on the front-end side.
=> SILA-2339: EIN validation message has been updated on front-end side.

src/components/common/SettingsModal.js
Hi @amack300,
- During the local testing I found that unable to update `App Handle` and `App Private Key` in the Demo App Setting popup, which was resolved in this PR and this happened because earlier changes were made related to these fields and here is the PR https://github.com/Sila-Money/sila-sdk-demo/pull/52/files
Please review and approve, it looks good to you!
Thanks!
=> SILA-2551: App Setting screen bug resolved.

src/components/context/AppDataProvider.js, src/components/home/KycModal.js, src/components/register/RegisterUserForm.js, src/constants/index.js, src/views/kyc/RegisterUser.js
- Retrieve KYC level UI and functionality have been integrated.
Thanks!
=> SILA-2466: Retrieve KYC level UI and functionality have been integrated.

src/assets/images/accordion_minus.svg, src/assets/images/accordion_plus.svg, src/assets/styles/_accordion.scss, src/assets/styles/_forms.scss, src/assets/styles/_overrides.scss, src/assets/styles/_table.scss, src/assets/styles/demo.scss, src/assets/styles/views/_registeruser.scss, src/components/common/AccordionItem.js, src/components/home/KycModal.js, src/components/register/DefaultKYCForm.js, src/components/register/InstantAchKYCForm.js, src/components/register/KYCLiteForm.js, src/components/register/ReceiveOnlyKYCForm.js, src/components/register/RegisterDataForm.js, src/components/register/RegisterUserForm.js, src/constants/index.js, src/routes/index.js, src/views/kyc/RegisterUser.js
- Integrated Registration data UI.
- Built User Retrieve data and integrated Registration data accordion and table components etc.
Thanks!
=> SILA-2324: Built User Retrieve data and integrated Registration data accordion and table components etc.

src/assets/styles/_dropdown.scss, src/components/common/SelectMenu.js, src/components/context/AppDataProvider.js, src/components/home/KybModal.js, src/components/kyb/RegisterBusinessForm.js, src/constants/index.js, src/views/kyb/RegisterBusiness.js
Hi @amack300,
The following things have been implemented.
- Choose your preferred KYB level screen has been integrated into the Business Information page as per the Figma screen.
- Also, If a business type is `Sole proprietorships`, `trusts`, and `unincorporated associations` in such case `KYB Standard` is `disabled` in the Choose preferred KYB drop-down menu.
Thanks!
=> SILA-2362: Choose your preferred KYB level screen has been integrated in the Business Information page.

src/assets/styles/_dropdown.scss, src/components/common/ConfirmModal.js, src/components/common/SelectMenu.js, src/components/context/AppDataProvider.js, src/components/home/KybModal.js, src/components/kyb/RegisterBusinessForm.js, src/components/register/RegisterDataForm.js, src/components/register/RegisterUserForm.js, src/constants/index.js, src/routes/index.js, src/views/kyb/RegisterBusiness.js, src/views/kyc/RegisterUser.js
Hi @amack300,
The following things have been implemented - 
- `Delete` - On clicking the delete icon, will prompt the modal box and once confirmed it will delete the field row and the row will be removed from the table list.
- `Delete` - On clicking the delete icon row first name, last name, etc these fields are required for registration which users can not be deleted so here we're going to show a message once confirmed to delete.
Thanks!
=> SILA-2332: Implemented Delete field functionality with confirm modal box.

src/components/kyb/KYBFormFieldType.js, src/components/kyb/RegisterBusinessDataForm.js, src/components/layout/MainSidebar.js, src/constants/index.js, src/routes/index.js
Hi @amack300,
In this PR the following things have been implemented for `Business User`:
`Edit` - On clicking the pencil icon data convert into the input field and on hitting enter key it will submit and also submit on clicking on the Save button.
`Edit` - clicking the pencil icon is a toggle and also input field convert to data if clicked outside the table or any body part.
- `Add data` to the new registration data functionality has been implemented.
- Added client-side validation on the registration form as per the choice preferred KYB.
Thanks!
=> SILA-2399: Built End user for Add Data and Edit screen.

src/components/kyb/KYBFormFieldType.js, src/components/kyb/RegisterBusinessDataForm.js, src/components/kyb/RegisterBusinessForm.js, src/components/layout/MainSidebar.js, src/constants/index.js, src/routes/index.js, src/views/kyb/RegisterBusiness.js
- Built for retrieve `Business Info` as per the Figma Screen functionality has been done.
=> SILA-2398: Built for retrieve Business Info as per the Figma Screen functionality has been done.

src/components/kyb/RegisterBusinessDataForm.js, src/constants/index.js, src/views/kyb/RegisterBusiness.js
Hi @amack300,
The following things have been implemented - 
- `Delete` - On clicking the delete icon, will prompt the modal box and once confirmed it will delete the field row and the row will be removed from the table list.
- `Delete` - On clicking the delete icon row `Legal Company Name`, `DBA` and `Business Website`, etc these fields are required for registration which users can not be deleted so here we're going to show a message once confirmed to delete.
Thanks!
=> SILA-2467: Implemented Delete field functionality with confirm modal box for Business Register info.

src/components/kyb/MemberKYBForm.js, src/components/kyb/RegisterBusinessDataForm.js, src/components/kyb/RegisterBusinessForm.js, src/components/register/DefaultKYCForm.js, src/components/register/RegisterDataForm.js, src/components/register/RegisterUserForm.js
Hi @amack300,
- Addressed `QA` issues.
Thanks!
=> SILA-2969: Addressed QA issues.

src/views/RequestKYC.js
Passed kyc_level param in requestKYC() function.
=> SILA-2971 KYC-LITE and Receive Only flow should not ask user for address at the time of request kyc. 

src/assets/styles/_dropdown.scss, src/components/kyb/RegisterBusinessDataForm.js, src/components/register/RegisterDataForm.js, src/views/Transact.js, src/views/kyb/RegisterMember.js
Hi @amack300,
Addressed `UI` issues as per the QA list out.
Thanks!
=> SILA-2978: Fixed UI issues as per QA listout.

src/views/Accounts.js
Hi @amack300,
- Link Account page - Button UI gets distorted after linking the bank account UI issue has been fixed.
Thanks!
=> SILA-2984: Link Account page - Button UI get distorted after linking the bank account UI issue has been fixed.

src/assets/styles/_dropdown.scss, src/views/kyb/BusinessType.js, src/views/kyb/RegisterMember.js
Hi @amack300,
- Business type dropdown values hide behind the header UI issue have been fixed.
Thanks!
=> SILA-2986: Business type dropdown values hide behind the header UI issue has been fixed.

src/components/kyb/LinkMemberForm.js, src/components/kyb/MemberKYBForm.js, src/views/Wallets.js, src/views/kyb/CertifyBusiness.js
Hi @amack300,
Addressed some issues:
- More Info Needed not popping up for Controlling Officer addressed.
- Also fixed the wallet name edit bug.
- In KYB flow with choosing a Receive Only in that case allowing the user to the next page without Certify business.
Thanks!
=> SILA-3028: More Info Needed not popping up for Controlling Officer need to be addressed.

src/components/home/KybKycModal.js, src/components/home/KycModal.js
Hi @amack300,
- Addressed the `spell` issues in the `KYC` and `KYB` modal box.
Thanks!
=> SILA-3091: Fixed the spell issues.

src/components/home/KybModal.js
KYB levels do not have set transaction limits.
=> SILA-3155: Remove tx limit descriptions

src/components/common/Loader.js, src/components/kyb/RegisterBusinessForm.js, src/components/register/RegisterUserForm.js
- Fixed issue, Loader should be shown at the center of the screen where the page is longer in height.
Thanks!
=> SILA-3037: Fixed issue, Loader should be shown at the center of the screen where page is longer in height.

src/assets/styles/_forms.scss, src/components/common/Loader.js, src/components/kyb/RegisterBusinessForm.js, src/components/register/RegisterUserForm.js, src/views/Transact.js
- Instead of a bad request, a proper validation message should be shown to the user when the issue or redeem 0 amount issue is fixed.
Thanks!
=> SILA-3153: Instead of a bad request, a proper validation message should be shown to the user when the issue or redeem 0 amount issue is fixed.

src/assets/styles/_forms.scss, src/components/common/Loader.js, src/components/kyb/RegisterBusinessForm.js, src/components/register/RegisterUserForm.js, src/views/Transact.js
- Unable to see previous transactions when no of the transaction is more than 20, now added max 50
Thanks!
=> SILA-3100: Unable to see previous transactions when no of the transaction is more than 20, now added max 50

src/assets/styles/_forms.scss, src/components/common/Loader.js, src/components/kyb/RegisterBusinessForm.js, src/components/register/RegisterUserForm.js, src/views/Accounts.js, src/views/Transact.js
- Unable to see Transaction response on response section issue fixed.
Thanks!
=> SILA-3101: Unable to see Transaction response on response section issue fixed.

src/views/Transact.js
get_sila_balance response  only show when the user click on the Refresh button
=> SILA-3061 Incorrect response messages displayed while sila issued or transferred. 

src/components/transact/TransactionsModal.js
=> SILA-3059 Update Transaction message for better User experience

src/views/Wallets.js
=> SILA-3058 When updating wallet name then its removing default wallet selection

src/components/kyb/LinkMemberForm.js
=> SILA-2279: Fixed Administrator link bug.

src/components/accounts/LinkAccountModal.js, src/components/register/RegisterDataForm.js, src/components/transact/TransactionsModal.js, src/utils/index.js, src/views/Accounts.js, src/views/kyb/CertifyBusiness.js
Hi @amack300,
- Demo Enhancement: Phase 2 - QA issues resolved
Thanks!
=> SILA-3170: Demo Enhancement : Phase 2 - QA issues resolved

src/components/register/RegisterDataForm.js, src/components/register/RegisterUserForm.js
Hi @amack300,
- Added a refresh button to check SMS confirmed status on the Registered Data page.
Thanks!
=> SILA-3193: Added a refresh button to check sms confirmed status on the Registered Data page.

src/components/home/KycModal.js, src/constants/index.js
Renamed Default KYC to Doc KYC.
=> SILA-3236: Renamed Default KYC to Doc KYC.

src/views/Wallets.js
Hi @amack300,
- Able to add multiple wallets with the same wallet name issue resolved.
Thanks!
=> SILA-3040: Able to add multiple wallets with same wallet name issue resolved.

src/components/wallets/Wallet.js, src/views/Wallets.js
Hi @amack300,
The following `wallet` page related issues have been resolved.
- Able to update wallet with more than 40 characters. `Ticket` #[SILA-3103](https://sila.atlassian.net/browse/SILA-3103) 
- Unable to delete additional wallet fields. `Ticket` #[SILA-3039](https://sila.atlassian.net/browse/SILA-3039)  
- make as default option should not be shown on the already default wallet. `Ticket` #[SILA-3032](https://sila.atlassian.net/browse/SILA-3032)  
- While updating the wallet name previously added wallet name was removed. `Ticket` #[SILA-3031](https://sila.atlassian.net/browse/SILA-3031)  
- Make as default link should not be visible when a user updates the wallet with more than 40 characters. `Ticket` #[SILA-3030](https://sila.atlassian.net/browse/SILA-3030)  
Thanks!
=> SILA-3103 - Resolved all the Wallet page related issues.

src/constants/index.js
Hi @amack300,
Demo - Change KYC level from default to DOC_KYC on DOC KYC failed in response issue fixed.
Thanks!
=> SILA-3256-hotfix: Demo - Change KYC level from default to DOC_KYC on DOC KYC failed in response issue fixed.

src/views/Transact.js
Hi @amack300,
- Resolved issue, Transfer sila transaction is not showing on the Transaction screen.
Thanks!
=> SILA-3262: Resolved issue, Transfer sila transaction is not showing on Transaction screen.

src/components/common/AlertMessage.js, src/components/documents/DocumentPreviewModal.js, src/components/documents/UploadDocumentModal.js, src/components/kyb/AddDataForm.js, src/components/kyb/RegisterBusinessForm.js, src/components/register/RegisterUserForm.js, src/views/DocumentUpload.js, src/views/RequestKYC.js, src/views/kyb/BusinessMembers.js
Hi @amack300,
Implement Document Preview UI and functionality except for preview document.
Thanks!
=> SILA-3206: Implement Document Preview UI and functionality except for preview document.

src/components/kyb/RegisterBusinessForm.js, src/components/register/RegisterUserForm.js, src/views/RequestKYC.js
Hi @amack300,
Disable Request KYC once KYC status is Pass ID verification.
Thanks!
=> SILA-3415: Disable Request KYC once KYC status is Pass ID verification.

src/views/Accounts.js
Hi @amack300,
Updated language on the `Link a Bank Account` page.
Thanks!
=> SILA-3358: Updated language on the Link a Bank Account page.

src/components/context/AppDataProvider.js, src/views/Accounts.js, src/views/RequestKYC.js
Hi @amack300,
Implemented `Check Partner KYC` on the `Request KYC/KYB` page.
Thanks!
=> SILA-3373: Implemented Check Partner KYC on the Request KYC/KYB page.

package.json, src/components/context/AppDataProvider.js, src/components/documents/UploadDocumentModal.js, src/constants/index.js, src/views/DocumentUpload.js
Hi @amack300,
Document Upload is now issue fixed. please review. and FYI there are some code commented which will be used for preview 
Thanks!
=> SILA-3663: Document Upload issue is now fixed.

src/views/RequestKYC.js
Hi @amack300,
Auto-refresh `KYC`/`KYB` status every 6 secs interval and max 3 times.
Thanks!
=> SILA-3594: Auto refresh KYC status every 6 secs interval and max 3 times.

src/routes/index.js, src/views/DocumentUpload.js, src/views/RequestKYC.js, src/views/Wallets.js, src/views/kyb/CertifyBusiness.js, src/views/kyc/RegisterUser.js
Hi @amack300 ,
Document Upload should be after Request KYC in the navigation flow changes done.
Thanks!
=> SILA-3682: Document Upload should be after Request KYC in the navigation flow changes done.

src/constants/index.js, src/views/Transact.js
Hi @amack300 ,
`Processing Type` dropdown and its functionality have been added on the `Transaction` page for the Issue and redeem transaction.
Thanks!
=> SILA-3456: Processing Type dropdown added on the Transaction page for the Issue and redeem transaction.

src/assets/styles/_modal.scss, src/views/Wallets.js
Hi @amack300 ,
On Upload, a Document model box Choose type dropdown open arrow is not matched with design UI issue fixed.
Thanks!
=> SILA-3726: On Upload, a Document model box Choose type dropdown open arrow is not matched with design UI issue fixed.

src/views/Accounts.js
Hi @amack300,
`Connect via paid Link` button is not working, if the user chooses to `Receive Only` KYC issue fixed.
Thanks!
=> SILA-3731: Connect via paid Link button is not working, if the user chooses to Receive Only KYC issue fixed.

src/views/RequestKYC.js
Hi @amack300 ,
The user got stuck on the request KYC screen when received KYC status as the document required issue fixed.
Thanks!
=> SILA-3746: User got stuck on the request kyc screen when received kyc status as document required issue fixed.

src/components/kyb/MemberKYBForm.js
Hi @amack300,
Incorrect validation is showing when the user entered the `SSN` number only a one-time issue has been fixed.
Thanks!
=> SILA-3732: Incorrect validation is showing when the user entered the SSN number only a one-time issue has been fixed.

src/components/home/KybModal.js, src/components/home/KycModal.js
Hi @amack300,
fixed typo spell issue.
Thanks!
=> SILA-3976: fixed typo spell issue.

package.json
Hi @amack300,
Upgraded `sila-sdk-javascript` npm module version in demo App for support `document preview`.
Thanks!
=> SILA-4008-upgrade-sila-sdk-javascript: Upgraded sila-sdk-javascript npm module version in demo App for support document preview.

src/components/accounts/InstitutionsModal.js
Hi @amack300 ,
Resolved white blank page is showing when searching with the blank space.
Thanks!
=> SILA-4007-error-on-institution-search-modal - Resolved white blank page is showing when searching with the blank space.

src/components/kyb/MemberKYBForm.js
Hi @amack300 ,
Continue button does not enable issue resolved.
Thanks!
=> SILA-4006-continue-button-enable-issue: Continue button does not enable issue resolved.

src/components/accounts/InstitutionsModal.js, src/views/Accounts.js, src/views/RequestKYC.js
Hi @amack300 ,
The white screen while searching institution and also resolved the Continue button disabled on the wallet page.
Thanks!
=> SILA-4024: The white screen while searching institution and also resolved Continue disabled on the wallet page.

src/views/Accounts.js
Hi @amack300 ,
Fixed Incorrect Link on Link Account page issue.
Thanks!
=> SILA-4037: Incorrect Link on Link Account page fixed.

src/views/RequestKYC.js
Hi @amack300 ,
Context updated as per the Figma UI.
Thanks!
=> SILA-4063: Context updated as per the Figma UI.

src/views/Transact.js
Hi @amack300 ,
Added validation on the `amount` input field.
Thanks!
=> SILA-4060: Added validation on the amount input field.

src/constants/index.js, src/views/RequestKYC.js
Hi @amack300,
Created Mock APP ID and User Handle for check partner KYC page.
=> SILA-4068: Created Mock APP ID and User Handle for check partner KYC page.

src/views/Transact.js
Hi @amack300,
On the Transact page fixed Account drop-down value overlapping issue in mobile site issue fixed.
Thanks!
=> SILA-2988: On the Transact page fixed Account drop-down value overlapping issue in mobile site issue fixed.

src/views/RequestKYC.js
Hi @amack300 ,
Updated text on the `Check Partner KYC` page.
Thanks!
=> SILA-4095: Updated text on the Check Partner KYC page.

src/assets/styles/views/_transact.scss, src/views/Transact.js
Hi @amack300 ,
Fixed Testing UI and function issues as per ticket.
Thanks!
=> SILA-4104: Fixed Testing UI and function issues.

src/components/accounts/LinkAccountModal.js, src/components/accounts/ProcessorTokenModal.js, src/views/Accounts.js
Hi @amack300,
`link_account` endpoint not showing in the `Response` Panel issue fixed.
Thanks!
=> SILA-4107 - link_account endpoint not showing in the Response Panel issue fixed.

src/views/Accounts.js
Hi @amack300,
Added `tooltip` to show link account type on the Link a Bank Account page.
Thanks!
=> SILA-4090: Added tooltip to show link account type on the Link a Bank Account page.

src/components/accounts/ProcessorTokenFlowModal.js, src/views/Accounts.js
Hi @amack300,
Added `Processor Token modal` in the `Processor Token Flow` modal.
Thanks!
=> SILA-4089: Added Processor Token modal in the Processor Token Flow modal.

src/components/accounts/ProcessorTokenFlowModal.js, src/views/Accounts.js
Hi @amack300,
Implemented `Processor Token Flow` Modal and removed the `PlaidButton` and its functionality.
Thanks!
=> SILA-4082: Implemented Processor Token Flow Modal.

.gitignore, package.json, server/index.js, server/package.json, src/api/api.js, src/api/plaid.js, src/components/accounts/GenerateProcessorTokenModal.js, src/components/accounts/ProcessorTokenFlowModal.js, src/utils/index.js, src/views/Accounts.js
Hi @amack300,
Created `Node` and `Express` server and added `Plaid` endpoints routes.
To start the backend server go to the server folder and run `npm start`
Thanks!
=> SILA-4086: Created Node, Express server and added Plaid endpoints routes.

src/components/accounts/ProcessorTokenFlowModal.js, src/components/accounts/processor/AccountContextual.js, src/components/accounts/processor/CreateLinkToken.js, src/components/accounts/processor/GenerateAccessToken.js, src/components/accounts/processor/GeneratePublicToken.js, src/components/accounts/processor/LinkProcessorToken.js, src/components/accounts/processor/RetrieveAccountCredentials.js, src/constants/plaidGenerateProcessor.js, src/views/Accounts.js
Hi @amack300,
Implement `Generate a Processor Token Tutorial` flow.
Thanks!
=> SILA-4083: Implement Generate a Processor Token Tutorial flow.

src/constants/index.js, src/views/RequestKYC.js
Hi @amack300,
Rollback `Checkpartner` KYC feature.
Thanks!
=> SILA-4595: Rollback Checkpartner KYC feature.

Dockerfile
https://sila.atlassian.net/browse/ENGRG-2166
=> ENGRG-2166 upgraded Docker image.
